apiVersion: apps/v1

kind: Deployment

metadata:
  name: firstproject
  labels:
    app: gamutkart
    version: v1

spec:
  replicas: 10

  selector:
    matchLabels:
      app: chrisk8spro

  template:
    metadata:
      labels:
        app: chrisk8spro
    spec:
      containers:
      - name: chris-project
        image: chrisdee10/k8s-project
        ports:
        - containerPort: 8080
        command: ["/bin/sh"]
        args:  ["-c", "/root/apache-tomcat-8.5.38/bin/startup.sh; while true; do sleep 1; done;"]   
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
