apiVersion: v1
kind: Service
metadata:
  name: gamukartloadbalancer
  labels:
    app: gamukart
    version: v.1.2.3

spec:
  type: LoadBalancer
  
  selector:
    app: chrisk8spro

  ports:
    - nodePort: 31000
      port: 8080
      targetPort: 8080 
